src/Entity/AbstractEntity.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

abstract class AbstractEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    protected ?int $id = null;

    #[Gedmo\Timestampable(on: 'create')]
    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE)]
    protected ?\DateTimeInterface $created_at = null;

    #[Gedmo\Timestampable(on: 'update')]
    #[ORM\Column(name: 'updated_at', nullable: true,  type: Types::DATETIME_MUTABLE)]
    protected ?\DateTimeInterface $updated_at = null;

    #[Gedmo\Timestampable(on: 'update', )]
    #[ORM\Column(name: 'removed_at', nullable: true,  type: Types::DATETIME_MUTABLE)]
    protected ?\DateTimeInterface $removed_at = null;

    #[ORM\Column(name: 'enabled', nullable: false,  type: Types::BOOLEAN)]
    protected ?bool $enabled = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getRemovedAt(): ?\DateTimeInterface
    {
        return $this->removed_at;
    }

    public function setRemovedAt(?\DateTimeInterface $removed_at): static
    {
        $this->removed_at = $removed_at;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(?bool $enabled): static
    {
        $this->enabled = $enabled;

        return $this;
    }

}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student extends AbstractEntity
{

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column]
    private ?int $payment = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $schedule = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comments = null;

    #[ORM\Column(length: 255)]
    private ?string $surname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dni = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(nullable: true)]
    private ?bool $has_image_rights_accepted = null;

    #[ORM\Column(nullable: true)]
    private ?bool $has_sepa_agreement_accepted = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    private ?Tariff $tariff = null;

    #[ORM\ManyToOne(targetEntity: Bank::class, inversedBy: 'students')]
    private ?Bank $bank = null;

    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'event_student')]
    private Collection $events;

    #[ORM\ManyToOne(inversedBy: 'students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $city = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    private ?Person $parent = null;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: Invoice::class)]
    private Collection $invoices;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: Receipt::class)]
    private Collection $receipts;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: ReceiptLine::class)]
    private Collection $receiptLines;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: InvoiceLine::class)]
    private Collection $invoiceLines;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->invoices = new ArrayCollection();
        $this->receipts = new ArrayCollection();
        $this->receiptLines = new ArrayCollection();
        $this->invoiceLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPayment(): ?int
    {
        return $this->payment;
    }

    public function setPayment(int $payment): static
    {
        $this->payment = $payment;

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(?string $schedule): static
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): static
    {
        $this->comments = $comments;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(?string $dni): static
    {
        $this->dni = $dni;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function isHasImageRightsAccepted(): ?bool
    {
        return $this->has_image_rights_accepted;
    }

    public function setHasImageRightsAccepted(?bool $has_image_rights_accepted): static
    {
        $this->has_image_rights_accepted = $has_image_rights_accepted;

        return $this;
    }

    public function isHasSepaAgreementAccepted(): ?bool
    {
        return $this->has_sepa_agreement_accepted;
    }

    public function setHasSepaAgreementAccepted(?bool $has_sepa_agreement_accepted): static
    {
        $this->has_sepa_agreement_accepted = $has_sepa_agreement_accepted;

        return $this;
    }

    public function getTariff(): ?Tariff
    {
        return $this->tariff;
    }

    public function setTariff(?Tariff $tariff): static
    {
        $this->tariff = $tariff;

        return $this;
    }

    public function getBank(): ?Bank
    {
        return $this->bank;
    }

    public function setBank(?Bank $bank): static
    {
        $this->bank = $bank;

        return $this;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): static
    {
        if (!$this->events->contains($event)) {
            $this->events->add($event);
            $event->addEventStudent($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): static
    {
        if ($this->events->removeElement($event)) {
            $event->removeEventStudent($this);
        }

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getParent(): ?Person
    {
        return $this->parent;
    }

    public function setParent(?Person $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setStudent($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getStudent() === $this) {
                $invoice->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Receipt>
     */
    public function getReceipts(): Collection
    {
        return $this->receipts;
    }

    public function addReceipt(Receipt $receipt): static
    {
        if (!$this->receipts->contains($receipt)) {
            $this->receipts->add($receipt);
            $receipt->setStudent($this);
        }

        return $this;
    }

    public function removeReceipt(Receipt $receipt): static
    {
        if ($this->receipts->removeElement($receipt)) {
            // set the owning side to null (unless already changed)
            if ($receipt->getStudent() === $this) {
                $receipt->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReceiptLine>
     */
    public function getReceiptLines(): Collection
    {
        return $this->receiptLines;
    }

    public function addReceiptLine(ReceiptLine $receiptLine): static
    {
        if (!$this->receiptLines->contains($receiptLine)) {
            $this->receiptLines->add($receiptLine);
            $receiptLine->setStudent($this);
        }

        return $this;
    }

    public function removeReceiptLine(ReceiptLine $receiptLine): static
    {
        if ($this->receiptLines->removeElement($receiptLine)) {
            // set the owning side to null (unless already changed)
            if ($receiptLine->getStudent() === $this) {
                $receiptLine->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, InvoiceLine>
     */
    public function getInvoiceLines(): Collection
    {
        return $this->invoiceLines;
    }

    public function addInvoiceLine(InvoiceLine $invoiceLine): static
    {
        if (!$this->invoiceLines->contains($invoiceLine)) {
            $this->invoiceLines->add($invoiceLine);
            $invoiceLine->setStudent($this);
        }

        return $this;
    }

    public function removeInvoiceLine(InvoiceLine $invoiceLine): static
    {
        if ($this->invoiceLines->removeElement($invoiceLine)) {
            // set the owning side to null (unless already changed)
            if ($invoiceLine->getStudent() === $this) {
                $invoiceLine->setStudent(null);
            }
        }

        return $this;
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/student')]
class StudentController extends AbstractController
{
    #[Route('/', name: 'app_student_index', methods: ['GET'])]
    public function index(StudentRepository $studentRepository): Response
    {
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_student_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('student/new.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_show', methods: ['GET'])]
    public function show(Student $student): Response
    {
        return $this->render('student/show.html.twig', [
            'student' => $student,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_student_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('student/edit.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_delete', methods: ['POST'])]
    public function delete(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/student/_delete_form.html.twig
<form method="post" action="{{ path('app_student_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn">Delete</button>
</form>

templates/student/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student{% endblock %}

{% block body %}
    <h1>Edit Student</h1>

    {{ include('student/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_student_index') }}">back to list</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student index{% endblock %}

{% block body %}
    <h1>Student index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Payment</th>
                <th>Schedule</th>
                <th>Comments</th>
                <th>Surname</th>
                <th>Birth_date</th>
                <th>Dni</th>
                <th>Phone</th>
                <th>Has_image_rights_accepted</th>
                <th>Has_sepa_agreement_accepted</th>
                <th>Id</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Removed_at</th>
                <th>Enabled</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.address }}</td>
                <td>{{ student.payment }}</td>
                <td>{{ student.schedule }}</td>
                <td>{{ student.comments }}</td>
                <td>{{ student.surname }}</td>
                <td>{{ student.birthDate ? student.birthDate|date('Y-m-d') : '' }}</td>
                <td>{{ student.dni }}</td>
                <td>{{ student.phone }}</td>
                <td>{{ student.hasImageRightsAccepted ? 'Yes' : 'No' }}</td>
                <td>{{ student.hasSepaAgreementAccepted ? 'Yes' : 'No' }}</td>
                <td>{{ student.id }}</td>
                <td>{{ student.createdAt ? student.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.updatedAt ? student.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.removedAt ? student.removedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.enabled ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_student_show', {'id': student.id}) }}">show</a>
                    <a href="{{ path('app_student_edit', {'id': student.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="18">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_student_new') }}">Create new</a>
{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Student{% endblock %}

{% block body %}
    <h1>Create new Student</h1>

    {{ include('student/_form.html.twig') }}

    <a href="{{ path('app_student_index') }}">back to list</a>
{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student{% endblock %}

{% block body %}
    <h1>Student</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ student.name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ student.email }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ student.address }}</td>
            </tr>
            <tr>
                <th>Payment</th>
                <td>{{ student.payment }}</td>
            </tr>
            <tr>
                <th>Schedule</th>
                <td>{{ student.schedule }}</td>
            </tr>
            <tr>
                <th>Comments</th>
                <td>{{ student.comments }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ student.surname }}</td>
            </tr>
            <tr>
                <th>Birth_date</th>
                <td>{{ student.birthDate ? student.birthDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Dni</th>
                <td>{{ student.dni }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ student.phone }}</td>
            </tr>
            <tr>
                <th>Has_image_rights_accepted</th>
                <td>{{ student.hasImageRightsAccepted ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Has_sepa_agreement_accepted</th>
                <td>{{ student.hasSepaAgreementAccepted ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ student.createdAt ? student.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ student.updatedAt ? student.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Removed_at</th>
                <td>{{ student.removedAt ? student.removedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Enabled</th>
                <td>{{ student.enabled ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_student_index') }}">back to list</a>

    <a href="{{ path('app_student_edit', {'id': student.id}) }}">edit</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}